spring:
  application:
    name: taskflow

  profiles:
    active: dev   # 기본 실행은 dev, 배포 시 prod로 변경

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: INFO
